# Seeded from https://github.com/jonhoo/configs/blob/master/gui/.config/alacritty/alacritty.yml

# shell = "/usr/local/bin/fish"

[window]
# TODO: tiling window manager?
# decorations = "none"
dimensions = { columns = 160, lines = 40 }

[scrolling]
# tmux keeps the session history
history = 0

[font]
# Previously used in macOS/iTerm2
# normal = { family = "Roboto Mono Light for Powerline", style = "Light" }
normal = { family = "Noto Sans Mono", style = "Regular" }
size = 16.0

[colors]
# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
draw_bold_text_with_bright_colors = false
primary = { background = '#1d2021', foreground = '#d5c4a1' }
cursor = { text = '#1d2021', cursor = '#d5c4a1' }
normal = { black = '#1d2021', red = '#fb4934', green = '#b8bb26', yellow = '#fabd2f', blue = '#83a598', magenta = '#d3869b', cyan = '#8ec07c', white = '#d5c4a1' }
bright = { black = '#665c54', red = '#fe8019', green = '#3c3836', yellow = '#504945', blue = '#bdae93', magenta = '#ebdbb2', cyan = '#d65d0e', white = '#fbf1c7' }
indexed_colors = [
	{ index = 16, color = '#fe8019' },
	{ index = 17, color = '#d65d0e' },
	{ index = 18, color = '#3c3836' },
	{ index = 19, color = '#504945' },
	{ index = 20, color = '#bdae93' },
	{ index = 21, color = '#ebdbb2' },
]

[keyboard]
bindings = [
	# Disable keyboard arrow keys to force my use of vi keybindings
	{ key = "ArrowLeft", action = "None" }, 
	{ key = "ArrowDown", action = "None" }, 
	{ key = "ArrowUp", action = "None" }, 
	{ key = "ArrowRight", action = "None" }, 
]
